# Generated by Django 3.0.5 on 2020-04-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200407_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='Subtitle',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
