# Generated by Django 3.0.5 on 2020-04-08 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_section_subtitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='test',
            new_name='text',
        ),
    ]
